name: Bug report
description: Report a broken issue.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        # Bug report

        Important to note that your issue may have already been reported before. Please check issues in https://github.com/yesseruser/YesserPackageUpdater/issues. If you find that it already exists, respond with a reaction or add any further information that may be helpful.

  - type: dropdown
    attributes:
      label: Type
      options:
        - Crash
        - Freezing
        - Performance
        - Cosmetic
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: How do you reproduce the issue?
      placeholder: 1. Open ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen? What should happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: If applicable, add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false
  - type: input
    attributes:
      label: Version
      description: The version you encountered this bug on. This is show when running `pip list` and finding `yesserpackageupdater`
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      description: The operating system you encountered this bug on.
    validations:
      required: true
  - type: markdown
    attributes:
      content: |
        ## Logs
        Logs can be found at the package install location (`<pip show yesserpackageupdater - Location>/yesserpackageupdater`).  
        Use the `--log-debug` argument to log debug logs.
        Use `--clear-log` to clear the log file before logging.
  - type: textarea
    attributes:
      label: Drag/upload your log files here.
      placeholder: Drag and drop the logs into this box.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Please add any additional information here.
    validations:
      required: false
