blank_issues_enabled: true
contact_links:
    - name: Suggestions or feature request
      url: https://github.com/Yesser-Studios/ypkgupgr/discussions/categories/ideas
      about: Got something you think should change or be added? Search for or start a new discussion!
