name: Feature request
description: Request a new feature.
body:
  - type: markdown
    attributes:
      value: |
        # Feature request

        Important to note that your request may have already been requested before. Please check issues in https://github.com/yesseruser/YesserPackageUpdater/issues. If you find that it already exists, respond with a reaction or add any further information that may be helpful.
        Also make sure the feature is not already implemented in the newest version.
  - type: textarea
    attributes:
      label: Feature description
      description: What would you like to see added into the package?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem relation
      description: Is your feature related to a problem? If so, please describe:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Please add any additional information here:
    validations:
      required: false
